feat(api): community and moderators for project feed
hydralite/hydralite pull request #145
Opened 2021-07-22 15:54 UTC by Angshu31

WARNING: Do not merge until this is tested

2021-07-22 18:59 UTC, firecraftgaming requested changes
seems good only problem right now is that the changes you did in JoinProjectArgs makes so that a user that joins can select their member role. I think its fine if you just remove the changes to that file

2021-07-22 19:04 UTC, firecraftgaming requested changes
and the changes to JoinProject is also not needed because a user that is joining shouldn't be able to ask for a role. You start as a member and then a staff team can change your role

2021-07-22 19:07 UTC, firecraftgaming requested changes
and add the default to type for member

2021-07-22 19:07 UTC, firecraftgaming commented on api/prisma/schema.prisma
> +  type ProjectMemberType
edit this line to have at the end of it `@default(communityMember)`

2021-07-23 03:22 UTC, ajhalili2006 reviewed
Not probably a PR review, but for commit <https://github.com/hydralite/hydralite/pull/145/commits/b6f3f20517dfc7705810f07b7484f0659f8e2160>, please reword it to something like this...

```
chore(global): synchorize with upstream's dev branch
```

..so the Commitlint CI will go green.

2021-07-23 08:13 UTC, Angshu31 commented
While the code looks like it should work, and TS doesn't throw any errors, can @fullstackslayer still test this? If I do it before you do, I'll comment here to let you know it works.

2021-07-23 09:59 UTC, fullstackslayer commented
> While the code looks like it should work, and TS doesn't throw any errors, can @fullstackslayer still test this? If I do it before you do, I'll comment here to let you know it works.

@Angshu31 Idk if I'll find time in the next 36 hours - I'm keeping busy with the notion doc and some personal stuff as well.

If I am able to check it out, I'll test it and inform you.

2021-07-23 10:02 UTC, Angshu31 commented
> > While the code looks like it should work, and TS doesn't throw any errors, can @fullstackslayer still test this? If I do it before you do, I'll comment here to let you know it works.
> 
> @Angshu31 Idk if I'll find time in the next 36 hours - I'm keeping busy with the notion doc and some personal stuff as well.
> 
> If I am able to check it out, I'll test it and inform you.

No problem. I might have tested it already by the time that you're ready to do it. I'll inform you if I do get around to testing it.

2021-07-27 00:27 UTC, fullstackslayer commented
@Angshu31 what's the current status of this implementation

2021-08-02 17:58 UTC, closed without merging