Update API, Improve Performance Based On DeepSource Analytics, Format Code, Write Docstrings
hydralite/hydralite pull request #150
Opened 2021-07-26 17:16 UTC by XtremeDevX

2021-07-28 08:20 UTC, fullstackslayer requested changes

2021-07-28 08:20 UTC, fullstackslayer commented on api/src/auth/util/fetchOauthClientInfo.ts
> + * Fetches the OAuth client info from the Auth0 account.
this function is to return the client id, secret, and callback URL based on the provider name u specify. 

e.g if I pass in "github" ill get back GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET from the env. just a little hack to simplify stuff. pls refactor the docstring to reflect this description.

2021-07-28 08:20 UTC, fullstackslayer commented on web/hoc/api/useConn.ts
> +  return useContext(UseApiConnectionContext).conn as any;
why can't we explicitly deem it defined? What's the need of `as any`. the non-null assertion is better practice.

2021-07-28 08:20 UTC, fullstackslayer commented on api/src/auth/util/discordAvatarUrl.ts
> + * Gets the Discord avatar URL for the given user ID.
change this to "given user avatar hash"

2021-07-30 07:20 UTC, XtremeDevX commented
@fullstackslayer can we merge this now

2021-07-30 08:10 UTC, fullstackslayer approved these changes
awesome tysm

2021-07-30 08:10 UTC, fullstackslayer commented
time to resolve conflicts 😩

2021-07-30 08:40 UTC, merged